{{- $chart_name := .Chart.Name }}
{{- $chart_version := .Chart.Version | replace "+" "_" }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ .Release.Name }}-cronjob"
  labels:
    chart: "{{ $chart_name }}-{{ $chart_version }}"
spec:
  concurrencyPolicy: {{ .Values.concurrencyPolicy | default "Allow" }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit | default 1 }}
  {{- if hasKey .Values "startingDeadlineSeconds" }}
  startingDeadlineSeconds: {{ .Values.startingDeadlineSeconds }}
  {{- end }}
  {{- if hasKey .Values "suspend" }}
  suspend: {{ .Values.suspend }}
  {{- end }}
  jobTemplate:
    spec:
      {{- if hasKey .Values "backoffLimit" }}
      backoffLimit: {{ .Values.backoffLimit }}
      {{- end }}
      {{- if hasKey .Values "activeDeadlineSeconds" }}
      activeDeadlineSeconds: {{ .Values.activeDeadlineSeconds }}
      {{- end }}
      {{- if hasKey .Values "ttlSecondsAfterFinished" }}
      ttlSecondsAfterFinished: {{ .Values.ttlSecondsAfterFinished }}
      {{- end }}
      template:
        metadata:
          {{- with .Values.podAnnotations }}
          annotations:
{{ toYaml . | indent 12 }}
          {{- end }}
          labels:
            app: {{ .Release.Name }}
            cron: {{ .Release.Name }}
            {{- with .Values.podLabels }}
{{ toYaml . | indent 12 }}
            {{- end }}
        spec:
        {{- if hasKey .Values "serviceAccount" }}
        {{- if hasKey .Values.serviceAccount "name" }}
          serviceAccountName: {{ .Values.serviceAccount.name }}
        {{- else }}
          serviceAccountName: {{ .Release.Name }}
        {{- end }}
        {{- end }}
        {{- if hasKey .Values "securityContext" }}
          {{- if .Values.securityContext.runAsUser }}
          securityContext:
            runAsUser: {{ .Values.securityContext.runAsUser }}
            {{- if .Values.securityContext.runAsGroup }}
            runAsGroup: {{ .Values.securityContext.runAsGroup }}
            {{- end }}
            {{- if .Values.securityContext.fsGroup }}
            fsGroup: {{ .Values.securityContext.fsGroup }}
            {{- end }}
          {{- end }}
        {{- end }}
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with .Values.priorityClassName }}
          priorityClassName: {{ . }}
          {{- end }}
          {{- with .Values.initContainers }}
          initContainers:
{{ toYaml . | indent 10 }}
          {{- end }}
          containers:
          - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.imagePullPolicy | default "IfNotPresent" }}
            name: {{ .Release.Name }}
            {{- with .Values.containerSecurityContext }}
            securityContext:
{{ toYaml . | indent 14 }}
            {{- end }}
            {{- with .Values.env }}
            env:
{{ toYaml . | indent 12 }}
            {{- end }}
            {{- with .Values.envFrom }}
            envFrom:
{{ toYaml . | indent 12 }}
            {{- end }}
            {{- with .Values.command }}
            command:
{{ toYaml . | indent 12 }}
            {{- end }}
            {{- with .Values.args }}
            args:
{{ toYaml . | indent 12 }}
            {{- end }}
            {{- with .Values.resources }}
            resources:
{{ toYaml . | indent 14 }}
            {{- end }}
            {{- with .Values.volumeMounts }}
            volumeMounts:
{{ toYaml . | indent 12 }}
            {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
{{ toYaml . | indent 12 }}
          {{- end }}
          restartPolicy: {{ .Values.restartPolicy | default "OnFailure" }}
          {{- with .Values.volumes }}
          volumes:
{{ toYaml . | indent 12 }}
          {{- end }}
  schedule: {{ .Values.schedule | quote }}
  {{- with .Values.timeZone }}
  timeZone: {{ . | quote }}
  {{- end }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit | default 3 }}
