{
 "title": "Loki Global Metrics",
 "description": "Loki Overview",
 "tags": [ "loki" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div class=\"left dashboard-header\">\n   <img src=\"https://marketplace-assets.digitalocean.com/logos/loki-logo.svg\" style=\"height:29px;\"/>\n  <span>Loki Global Metrics</span>\n</div>"
   }
  },
  {
   "title": "Loki Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "loki_build_info" }
   ]
  },
  {
   "title": "Message Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(loki_log_messages_total)" }
   ]
  },
  {
   "title": "Current Alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "prometheus_notifications_alertmanagers_discovered"
    }
   ]
  },
  {
   "title": "Alerts Event Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "prometheus_notifications_sent_total"
    }
   ]
  },
  {
   "title": "Store Series Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(loki_store_series_total)" }
   ]
  },
  {
   "title": "Store Chunks Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(loki_ingester_chunk_stored_bytes_total)"
    }
   ]
  },
  {
   "title": "Rules Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_rule_group_rules)"
    }
   ]
  },
  {
   "title": "Panic ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "loki_panic_total" }
   ]
  },
  {
   "title": "Messages Input",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(loki_log_messages_total[1m])) by (level)",
     "legendFormat": "{{ level }}"
    }
   ]
  },
  {
   "title": "LogQL Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_logql_querystats_latency_seconds_bucket[5m])) by (le,type))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "API Request Durations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_request_duration_seconds_bucket[5m])) by (le,route))",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  {
   "title": "LogQL  Processed bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_logql_querystats_bytes_processed_per_seconds_bucket[5m])) by (le,type))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  { "title": "Ruler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Rules Status ",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(prometheus_rule_evaluations_total[5m])",
     "legendFormat": "Evaluations"
    },
    {
     "expr": "rate(prometheus_notifications_sent_total[5m])",
     "legendFormat": "Notifications"
    }
   ]
  },
  {
   "title": "Notifications Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_notifications_latency_seconds[5m]))  by (quantile)",
     "legendFormat": "TP {{quantile}}"
    }
   ]
  },
  {
   "title": "Rule Evaluations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_rule_evaluation_duration_seconds[5m]))  by (quantile)",
     "legendFormat": "TP {{quantile}}"
    }
   ]
  },
  { "title": "Cache ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Cache Request  Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_cache_request_duration_seconds_bucket[5m])) by (le,name,method))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Cache Value Size bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_cache_value_size_bytes_bucket[5m])) by (le,name,method))",
     "legendFormat": "{{name}} / {{method}}"
    }
   ]
  },
  {
   "title": "Hits Keys",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "rate(loki_cache_hits[5m])", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Chunk Store Chunks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_chunk_store_chunks_per_query_bucket[5m])) by (le))",
     "legendFormat": "chunks"
    }
   ]
  },
  {
   "title": "Fetched Keys",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "loki_cache_fetched_keys", "legendFormat": "{{name}}" }
   ]
  },
  { "title": "Index", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Distributor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Received Lines / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "sum by (tenant) (rate(loki_distributor_lines_received_total[5m]))",
       "legendFormat": "distributor / {{ tenant}}"
      }
     ]
    },
    {
     "title": "Distributor  Received bytes / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 45 },
     "targets": [
      {
       "expr": "sum(rate(loki_distributor_bytes_received_total[5m])) by (tenant)",
       "legendFormat": "distributor / {{tenant}}"
      }
     ]
    },
    {
     "title": "batch appends sent to ingesters / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 45 },
     "targets": [
      {
       "expr": "rate(loki_distributor_ingester_appends_total[5m])",
       "legendFormat": "successed"
      },
      {
       "expr": "loki_distributor_ingester_append_failures_total",
       "legendFormat": "failed"
      }
     ]
    },
    {
     "title": "Store Series / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (status) (rate(loki_store_series_total[5m]))",
       "legendFormat": "{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ingster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Blocks / Chunk",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_blocks_per_chunk_bucket[5m])) by (le))",
       "legendFormat": "blocks"
      }
     ]
    },
    {
     "title": "Chunk Size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 52 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_size_bytes_bucket[5m])) by (le))",
       "legendFormat": "chunk size"
      }
     ]
    },
    {
     "title": "Chunk Age",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 52 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_age_seconds_bucket[5m])) by (le))",
       "legendFormat": "ages"
      }
     ]
    },
    {
     "title": "Chunk Compression Ratios",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 58 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_compression_ratio_bucket[5m])) by (le))",
       "legendFormat": "ratio"
      }
     ]
    },
    {
     "title": "Chunk Encode Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 58 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_encode_time_seconds_bucket[5m])) by (le))",
       "legendFormat": "durations."
      }
     ]
    },
    {
     "title": "Lines / Chunk",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 58 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_entries_bucket[5m])) by (le))",
       "legendFormat": "lines"
      }
     ]
    },
    {
     "title": "Chunk Status",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 64 },
     "targets": [
      {
       "expr": "rate(loki_ingester_chunks_created_total[5m])",
       "legendFormat": "create"
      },
      {
       "expr": "sum by (reason) (rate(loki_ingester_chunks_flushed_total[5m]))",
       "legendFormat": "flush / {{ reason }}"
      },
      {
       "expr": "sum by (fake) (rate(loki_ingester_chunks_stored_total[5m]))",
       "legendFormat": "stored"
      },
      {}
     ]
    },
    {
     "title": "Chunks in Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 64 },
     "targets": [
      { "expr": "loki_ingester_memory_chunks", "legendFormat": "chunks" }
     ]
    },
    {
     "title": "Chunks in Streams",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 64 },
     "targets": [
      {
       "expr": "sum by (tenan) (loki_ingester_memory_streams)",
       "legendFormat": "streams"
      }
     ]
    },
    {
     "title": "Strams Stats",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 70 },
     "targets": [
      {
       "expr": "rate(loki_ingester_streams_created_total[5m])",
       "legendFormat": "create"
      },
      {
       "expr": "rate(loki_ingester_streams_removed_total[5m])",
       "legendFormat": "delete"
      }
     ]
    }
   ]
  }
 ]
}