{
 "title": "Prometheus / Overview",
 "tags": [ "Prometheus" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "60s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(prometheus_build_info,job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(prometheus_build_info{job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Prometheus Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Prometheus Stats",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (cluster, job, instance, version) (prometheus_build_info{job=~\"$job\", instance=~\"$instance\"})"
    },
    {
     "expr": "max by (cluster, job, instance) (time() - process_start_time_seconds{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  { "title": "Discovery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Target Sync",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_target_sync_length_seconds_sum{job=~\"$job\",instance=~\"$instance\"}[5m])) by (job, scrape_job, instance) * 1e3",
     "legendFormat": "{{scrape_job}}"
    }
   ]
  },
  {
   "title": "Targets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (cluster, job, instance) (prometheus_sd_discovered_targets{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "{{cluster}}:{{job}}:{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Profile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=\"$job\"})",
     "legendFormat": "p8s process resident memory"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"$job\"}",
     "legendFormat": "virtual memory"
    }
   ]
  },
  { "title": "Retrieval", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Average Scrape Interval Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(prometheus_target_interval_length_seconds_sum{job=~\"$job\",instance=~\"$instance\"}[5m]) / rate(prometheus_target_interval_length_seconds_count{job=~\"$job\",instance=~\"$instance\"}[5m]) * 1e3",
     "legendFormat": "{{instance}} {{interval}} configured"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(5, max(scrape_duration_seconds) by (job))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Appended Samples",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total{job=~\"$job\",instance=~\"$instance\", type=\"float\"}[5m])",
     "legendFormat": "{{cluster}} {{job}} {{instance}}"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Head Series",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "prometheus_tsdb_head_series{job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "{{job}} {{instance}} head series"
      }
     ]
    },
    {
     "title": "Head Chunks",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "prometheus_tsdb_head_chunks{job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "{{job}} {{instance}} head chunks"
      }
     ]
    }
   ]
  },
  { "title": "Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Query Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(prometheus_engine_query_duration_seconds_count{job=~\"$job\",instance=~\"$instance\",slice=\"inner_eval\"}[5m])",
     "legendFormat": "{{job}} {{instance}}"
    }
   ]
  },
  {
   "title": "Stage Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by (slice) (prometheus_engine_query_duration_seconds{quantile=\"0.9\",job=~\"$job\",instance=~\"$instance\"}) * 1e3",
     "legendFormat": "{{slice}}"
    }
   ]
  }
 ]
}