version: '3'

tasks:
  default:
    desc: "Display all available tasks for this project"
    silent: true
    cmds:
      - task --list-all

  generate:
    desc: Generate Helm charts
    silent: true
    cmds:
      - |
        for chart in charts/*/Chart.yaml; do
          chart_dir=$(dirname "$chart")
          helm dependency update "$chart_dir" || true
          helm package "$chart_dir" -d docs/
        done
      - helm repo index docs/ --url "https://freuds.github.io/custom-charts/" --merge docs/index.yaml

  lint:
    desc: Lint Helm charts
    silent: true
    cmds:
      - ct lint --config charts/ct.yaml

  lint-all:
    desc: Lint et valide dynamiquement tous les charts listés dans chart-dirs de ct.yaml
    silent: true
    cmds:
      - task: lint
      - |
        for chart in $(yq '.chart-dirs[]' charts/ct.yaml); do
          helm lint charts/$chart
          helm template charts/$chart | \
            kubeconform -kubernetes-version 1.26.0 \
            -schema-location default \
            -schema-location 'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json'
        done

  update-deps:
    desc: Update Helm dependencies
    cmds:
      - |
        for chart in $(yq '.chart-dirs[]' charts/ct.yaml); do
          helm dependency update charts/$chart
        done
