{
 "title": "Gateway API State / Gateways",
 "description": "Visualisation of kubernetes Gateway API Gateway resources in your cluster.",
 "tags": [
  "gateway-api",
  "gateway-api-state"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "gateway",
    "label": "Gateway",
    "query": {
     "query": "label_values(gatewayapi_gateway_info, name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Gateways", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total",
   "type": "stat",
   "description": "Total number of Gateways across all namespaces",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gatewayapi_gateway_info{name=~\"$gateway\"})"
    }
   ]
  },
  {
   "title": "Unhealthy",
   "type": "stat",
   "description": "Number of Gateways not in an Accepted and Programmed state",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((gatewayapi_gateway_status{name=~\"$gateway\",type=\"Accepted\"} == 0) or (gatewayapi_gateway_status{name=~\"$gateway\",type=\"Programmed\"} == 0)) or vector(0)"
    }
   ]
  },
  {
   "title": "Gateways",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gatewayapi_gateway_created{name=~\"$gateway\"} * on(name, namespace, instance) group_right gatewayapi_gateway_info{name=~\"$gateway\"}"
    }
   ]
  },
  {
   "title": "Gateway Listeners",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gatewayapi_gateway_listener_info{name=~\"$gateway\"}"
    }
   ]
  },
  {
   "title": "Accepted",
   "type": "stat",
   "description": "Total Gateways with an Accepted state of True",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gatewayapi_gateway_status{name=~\"$gateway\",type=\"Accepted\"} > 0)"
    }
   ]
  },
  {
   "title": "Programmed",
   "type": "stat",
   "description": "Total Gateways with a Programmed state of True",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gatewayapi_gateway_status{name=~\"$gateway\",type=\"Programmed\"} > 0)"
    }
   ]
  },
  {
   "title": "Listeners",
   "type": "stat",
   "description": "Total number of listeners across all Gateways",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gatewayapi_gateway_listener_info{name=~\"$gateway\"})"
    }
   ]
  },
  {
   "title": "Att. Routes",
   "type": "stat",
   "description": "Total number of attached routes across all listeners",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gatewayapi_gateway_status_listener_attached_routes{name=~\"$gateway\"})"
    }
   ]
  },
  {
   "title": "Gateway Status Addresses",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gatewayapi_gateway_status_address_info{name=~\"$gateway\"}"
    }
   ]
  },
  {
   "title": "Gateway Listener Status - Attached Routes",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gatewayapi_gateway_status_listener_attached_routes{name=~\"$gateway\"}"
    }
   ]
  },
  {
   "title": "HTTPRoutes (by Gateway)",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gatewayapi_httproute_parent_info{parent_kind=\"Gateway\",parent_name=~\"${gateway}\"}"
    }
   ]
  },
  {
   "title": "GRPCRoutes (by Gateway)",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gatewayapi_grpcroute_parent_info{parent_kind=\"Gateway\",parent_name=~\"${gateway}\"}"
    }
   ]
  },
  {
   "title": "TLSRoutes (by Gateway)",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gatewayapi_tlsroute_parent_info{parent_kind=\"Gateway\",parent_name=~\"${gateway}\"}"
    }
   ]
  },
  {
   "title": "TCPRoutes (by Gateway)",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gatewayapi_tcproute_parent_info{parent_kind=\"Gateway\",parent_name=~\"${gateway}\"}"
    }
   ]
  },
  {
   "title": "UDPRoutes (by Gateway)",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gatewayapi_udproute_parent_info{parent_kind=\"Gateway\",parent_name=~\"${gateway}\"}"
    }
   ]
  }
 ]
}