{
 "title": "OpenVPN Server",
 "description": "OpenVPN Server status using Prometheus and OpenVPN exporter ",
 "tags": [ "openvpn" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Top Logins",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(6, sum(rate(openvpn_server_client_received_bytes_total{common_name!=\"UNDEF\"}[1d])) by (common_name, connection_time, real_address))",
     "legendFormat": "{{ common_name }} {{real_address}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openvpn_up{job=\"openvpn-exporter\"}"
    }
   ]
  },
  {
   "title": "Top 6 Client Network Activity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(6, sum(rate(openvpn_server_client_received_bytes_total{job=\"openvpn-exporter\",common_name!=\"UNDEF\"}[$__interval])) by (common_name))",
     "legendFormat": "{{ common_name }} - Rx"
    },
    {
     "expr": "topk(6, sum(rate(openvpn_server_client_sent_bytes_total{job=\"openvpn-exporter\",common_name!=\"UNDEF\"}[$__interval])) by (common_name))",
     "legendFormat": "{{ common_name }} - Tx"
    }
   ]
  },
  {
   "title": "Clients Connected",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(openvpn_server_connected_clients{job=\"openvpn-exporter\"})"
    }
   ]
  },
  {
   "title": "Status Update Since",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-openvpn_status_update_time_seconds{job=\"openvpn-exporter\"}"
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openvpn_server_connected_clients{job=\"openvpn-exporter\"}",
     "legendFormat": "Client(s)"
    }
   ]
  },
  {
   "title": "Top Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(6, sum(increase(openvpn_server_client_received_bytes_total{common_name!=\"UNDEF\"}[1d])+increase(openvpn_server_client_sent_bytes_total{common_name!=\"UNDEF\"}[1d]))by(common_name))",
     "legendFormat": "{{ common_name }}"
    }
   ]
  },
  {
   "title": "Traffic Distribution",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(sum(increase(openvpn_server_client_received_bytes_total{common_name!=\"UNDEF\"}[1d])+increase(openvpn_server_client_sent_bytes_total{common_name!=\"UNDEF\"}[1d]))by(common_name))",
     "legendFormat": "{{ common_name }}"
    }
   ]
  },
  {
   "title": "Total Received (Bytes)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(openvpn_server_client_received_bytes_total[1d]))",
     "legendFormat": "Total Received"
    }
   ]
  },
  {
   "title": "Total Sent (Bytes)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(openvpn_server_client_sent_bytes_total[1d]))"
    }
   ]
  },
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(openvpn_server_client_received_bytes_total{job=\"openvpn-exporter\",common_name=~\"[a-zA-Z0-9]*\"}) or absent(count(openvpn_server_client_received_bytes_total{job=\"openvpn-exporter\",common_name=~\"[a-zA-Z0-9]*\"}))-1"
    }
   ]
  },
  {
   "title": "Current OpenVPN Clients",
   "type": "table",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sort_desc(sum(rate(openvpn_server_client_received_bytes_total{job=\"openvpn-exporter\",common_name!=\"UNDEF\"}[5m])) by (common_name, connection_time, virtual_address, real_address))",
     "legendFormat": "Tx"
    },
    {
     "expr": "sum(rate(openvpn_server_client_sent_bytes_total{job=\"openvpn-exporter\",common_name!=\"UNDEF\"}[5m])) by (common_name, connection_time, virtual_address, real_address)",
     "legendFormat": "Rx"
    }
   ]
  }
 ]
}