{
 "title": "Synology NAS Details",
 "description": "Synology NAS dashboard utilizing Prometheus snmp_exporter (https://github.com/prometheus/snmp_exporter)",
 "tags": [
  "synology",
  "dsm",
  "nas"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "JobName", "label": "Job Name", "query": { "query": "label_values(ssCpuUser, job)" } },
   {
    "name": "Device",
    "query": {
     "query": "query_result(ssCpuUser{job=~'$JobName'})"
    }
   },
   {
    "name": "Interface",
    "query": {
     "query": "label_values(ifName{job=~'$JobName',instance=~'$Device'},ifName)"
    }
   },
   {
    "name": "raidName",
    "label": "Storage",
    "query": {
     "query": "label_values(raidName{job=~'$JobName',instance=~'$Device'},raidName)"
    }
   },
   {
    "name": "storageIODevice",
    "label": "Disk",
    "query": {
     "query": "label_values(storageIODevice{job=~'$JobName',instance=~'$Device'},storageIODevice)"
    }
   },
   {
    "name": "spaceIODevice",
    "label": "Volume Name",
    "query": {
     "query": "label_values(spaceIODevice{job=~'$JobName',instance=~'$Device'},spaceIODevice)"
    }
   },
   {
    "name": "hrStorageDescr",
    "label": "File System",
    "query": {
     "query": "label_values(hrStorageDescr{job=~'$JobName',instance=~'$Device'},hrStorageDescr)"
    }
   },
   {
    "name": "flashCacheDisk",
    "label": "Cache",
    "query": {
     "query": "label_values(flashCacheSSDDev{job=~'$JobName',instance=~'$Device'},flashCacheSSDDev)"
    }
   },
   {
    "name": "hrMemoryDescr",
    "label": "Memory",
    "query": {
     "query": "label_values(hrStorageDescr{job=~'$JobName',instance=~'$Device'},hrStorageDescr)"
    }
   },
   {
    "name": "SmartDev",
    "label": "S.M.A.R.T",
    "query": {
     "query": "label_values(diskSMARTInfoDevName{job=~'$JobName',instance=~'$Device'},diskSMARTInfoDevName)"
    }
   },
   {
    "name": "services",
    "query": {
     "query": "label_values(serviceName{job=~'$JobName',instance=~'$Device'},serviceName)"
    }
   },
   { "name": "interfacebits", "query": "8" }
  ]
 },
 "panels": [
  { "title": "System State - ($Device)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sysUpTime{job=~'$JobName',instance=~'$Device'}/100",
     "legendFormat": "uptime"
    },
    {
     "expr": "upgradeAvailable{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "temperature{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "cpuFanStatus{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "systemFanStatus{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "systemStatus{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "powerStatus{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "modelName{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "version{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "serialNumber{job=~'$JobName',instance=~'$Device'}"
    }
   ]
  },
  {
   "title": "CPU Usage - ($Device)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ssCpuUser{job=~'$JobName',instance=~'$Device'} + ssCpuSystem{job=~'$JobName',instance=~'$Device'}",
     "legendFormat": "Used"
    },
    {
     "expr": "100-(ssCpuUser{job=~'$JobName',instance=~'$Device'} + ssCpuSystem{job=~'$JobName',instance=~'$Device'})",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Usage - ($Device)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(memTotalReal{job=~'$JobName',instance=~'$Device'} - (memAvailReal{job=~'$JobName',instance=~'$Device'} + memCached{job=~'$JobName',instance=~'$Device'} + memBuffer{job=~'$JobName',instance=~'$Device'})) / memTotalReal{job=~'$JobName',instance=~'$Device'}",
     "legendFormat": "Used"
    },
    {
     "expr": "1-((memTotalReal{job=~'$JobName',instance=~'$Device'} - (memAvailReal{job=~'$JobName',instance=~'$Device'} + memCached{job=~'$JobName',instance=~'$Device'} + memBuffer{job=~'$JobName',instance=~'$Device'})) / memTotalReal{job=~'$JobName',instance=~'$Device'})",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "CPU Utilization - ($Device)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ssCpuSystem{job=~'$JobName',instance=~'$Device'}",
     "legendFormat": "System"
    },
    {
     "expr": "ssCpuUser{job=~'$JobName',instance=~'$Device'}",
     "legendFormat": "User"
    },
    {
     "expr": "ssCpuIdle{job=~'$JobName',instance=~'$Device'}",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Physical Memory - ($Device)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "memTotalReal{job=~'$JobName',instance=~'$Device'} ",
     "legendFormat": "Size"
    },
    {
     "expr": "memTotalReal{job=~'$JobName',instance=~'$Device'} - (memShared{job=~'$JobName',instance=~'$Device'} + memCached{job=~'$JobName',instance=~'$Device'} + memBuffer{job=~'$JobName',instance=~'$Device'} + memAvailReal{job=~'$JobName',instance=~'$Device'})",
     "legendFormat": "Reserved"
    },
    {
     "expr": "memBuffer{job=~'$JobName',instance=~'$Device'}",
     "legendFormat": "Buffer"
    },
    {
     "expr": "memCached{job=~'$JobName',instance=~'$Device'}",
     "legendFormat": "Cached"
    },
    {
     "expr": "memShared{job=~'$JobName',instance=~'$Device'}",
     "legendFormat": "Shared"
    },
    {
     "expr": "memAvailReal{job=~'$JobName',instance=~'$Device'}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "CPU Load - ($Device)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "laLoadInt{job=~'$JobName',instance=~'$Device'}/100",
     "legendFormat": "{{laNames}}"
    }
   ]
  },
  {
   "title": "Virtual Memory - ($Device)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "memTotalReal{job=~'$JobName',instance=~'$Device'} + memTotalSwap{job=~'$JobName',instance=~'$Device'}",
     "legendFormat": "Size"
    },
    {
     "expr": "(memTotalReal{job=~'$JobName',instance=~'$Device'} + memTotalSwap{job=~'$JobName',instance=~'$Device'}) - memTotalFree{job=~'$JobName',instance=~'$Device'}",
     "legendFormat": "Used"
    },
    {
     "expr": "memTotalFree{job=~'$JobName',instance=~'$Device'}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Processes - ($Device)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hrSystemProcesses{job=~'$JobName',instance=~'$Device'}",
     "legendFormat": "Processes"
    }
   ]
  },
  {
   "title": "Users / Service - ($Device)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "serviceUsers{job=~'$JobName',instance=~'$Device',serviceName=~'$services'}",
     "legendFormat": "{{serviceName}}"
    }
   ]
  },
  { "title": "System Internals - ($Device)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Network Interfaces - ($Device)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "ifPhysAddress{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}"
    },
    {
     "expr": "ifAdminStatus{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}"
    },
    {
     "expr": "ifSpeed{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}"
    },
    {
     "expr": "ifOperStatus{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}"
    },
    {
     "expr": "ifMtu{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}"
    }
   ]
  },
  {
   "title": "Hard Drives  - ($Device)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "diskTemperature{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "diskType{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "diskStatus{job=~'$JobName',instance=~'$Device'}"
    },
    {
     "expr": "diskModel{job=~'$JobName',instance=~'$Device'}"
    }
   ]
  },
  { "title": "Storage: $raidName - ($Device)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 }, "repeat": "raidName" },
  {
   "title": "RAID Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "raidStatus{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}"
    }
   ]
  },
  {
   "title": "Storage Usage - $raidName ($Device)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "raidTotalSize{job='$JobName',instance='$Device',raidName='$raidName'}",
     "legendFormat": "Size"
    },
    {
     "expr": "(raidTotalSize{job='$JobName',instance='$Device',raidName='$raidName'}-raidFreeSize{job='$JobName',instance='$Device',raidName='$raidName'})",
     "legendFormat": "Used"
    },
    {
     "expr": "raidFreeSize{job='$JobName',instance='$Device',raidName='$raidName'}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Storage Size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "raidTotalSize{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}"
    }
   ]
  },
  {
   "title": "% Used Space",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((raidTotalSize{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'}-raidFreeSize{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'})/raidTotalSize{job=~'$JobName',instance=~'$Device',raidName=~'$raidName'})*100",
     "legendFormat": "% Free"
    }
   ]
  },
  {
   "title": "File Systems: $hrStorageDescr ($Device)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "repeat": "hrStorageDescr",
   "collapsed": true,
   "panels": [
    {
     "title": "File System Size",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hrStorageSize{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrStorageDescr'} * hrStorageAllocationUnits{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrStorageDescr'}"
      }
     ]
    },
    {
     "title": "File System Usage: $hrStorageDescr ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 21, "x": 3, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "hrStorageSize{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrStorageDescr'} * hrStorageAllocationUnits{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrStorageDescr'}",
       "legendFormat": "Size"
      },
      {
       "expr": "hrStorageUsed{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrStorageDescr'} * hrStorageAllocationUnits{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrStorageDescr'}",
       "legendFormat": "Used"
      },
      {
       "expr": "(hrStorageSize{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrStorageDescr'} -  hrStorageUsed{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrStorageDescr'}) * hrStorageAllocationUnits{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrStorageDescr'}\n",
       "legendFormat": "Free"
      }
     ]
    }
   ]
  },
  {
   "title": "HDD/SSD: $storageIODevice - ($Device)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "repeat": "storageIODevice",
   "collapsed": true,
   "panels": [
    {
     "title": "Bits Read/Write: $storageIODevice - ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 152 },
     "targets": [
      {
       "expr": "rate(storageIONReadX{job=~'$JobName',instance=~'$Device',storageIODevice=~'$storageIODevice'}[$__rate_interval])",
       "legendFormat": "Read Bits"
      },
      {
       "expr": "rate(storageIONWrittenX{job=~'$JobName',instance=~'$Device',storageIODevice=~'$storageIODevice'}[$__rate_interval])",
       "legendFormat": "Write Bits"
      }
     ]
    },
    {
     "title": "I/O: $storageIODevice - ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 152 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(storageIOLA{job=~'$JobName',instance=~'$Device',storageIODevice=~'$storageIODevice'}[$__rate_interval])",
       "legendFormat": "I/0"
      },
      {
       "expr": "rate(storageIOLA1{job=~'$JobName',instance=~'$Device',storageIODevice=~'$storageIODevice'}[$__rate_interval])",
       "legendFormat": "I/O 1 min avg"
      },
      {
       "expr": "rate(storageIOLA5{job=~'$JobName',instance=~'$Device',storageIODevice=~'$storageIODevice'}[$__rate_interval])",
       "legendFormat": "I/O 5 min avg"
      },
      {
       "expr": "rate(storageIOLA15{job=~'$JobName',instance=~'$Device',storageIODevice=~'$storageIODevice'}[$__rate_interval])",
       "legendFormat": "I/O 15  min avg"
      }
     ]
    },
    {
     "title": "Load: $storageIODevice - ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 158 },
     "targets": [
      {
       "expr": "irate(storageIOReads{job=~'$JobName',instance=~'$Device',storageIODevice=~'$storageIODevice'}[$__rate_interval])",
       "legendFormat": "Read Load"
      },
      {
       "expr": "irate(storageIOWrites{job=~'$JobName',instance=~'$Device',storageIODevice=~'$storageIODevice'}[$__rate_interval])",
       "legendFormat": "Write Load"
      }
     ]
    }
   ]
  },
  {
   "title": "SSD Cache: $flashCacheDisk - ($Device)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "repeat": "flashCacheDisk",
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes Read/Write: $flashCacheDisk- ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 264 },
     "targets": [
      {
       "expr": "rate(flashCacheDiskRead{job=~'$JobName',instance=~'$Device',flashCacheSSDDev=~'$flashCacheDisk'}[$__rate_interval])",
       "legendFormat": "Read Bytes"
      },
      {
       "expr": "rate(flashCacheDiskWrite{job=~'$JobName',instance=~'$Device',flashCacheSSDDev=~'$flashCacheDisk'}[$__rate_interval])",
       "legendFormat": "Written Bytes"
      }
     ]
    },
    {
     "title": "Read/Write Hits: $flashCacheDisk- ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 264 },
     "targets": [
      {
       "expr": "rate(flashCacheReadHits{job=~'$JobName',instance=~'$Device',flashCacheSSDDev=~'$flashCacheDisk'}[$__rate_interval])",
       "legendFormat": "Read Hits"
      },
      {
       "expr": "rate(flashCacheWriteHits{job=~'$JobName',instance=~'$Device',flashCacheSSDDev=~'$flashCacheDisk'}[$__rate_interval])",
       "legendFormat": "Write Hits"
      }
     ]
    },
    {
     "title": "Read/Write Total: $flashCacheDisk- ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 270 },
     "targets": [
      {
       "expr": "rate(flashCacheTotalRead{job=~'$JobName',instance=~'$Device',flashCacheSSDDev=~'$flashCacheDisk'}[$__rate_interval])",
       "legendFormat": "Total Read Hits"
      },
      {
       "expr": "rate(flashCacheTotalWrite{job=~'$JobName',instance=~'$Device',flashCacheSSDDev=~'$flashCacheDisk'}[$__rate_interval])",
       "legendFormat": "Total Write Hits"
      }
     ]
    },
    {
     "title": "Read/Write Hit Rate: $flashCacheDisk- ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 270 },
     "targets": [
      {
       "expr": "rate(flashCacheReadHitRate{job=~'$JobName',instance=~'$Device',flashCacheSSDDev=~'$flashCacheDisk'}[$__rate_interval])",
       "legendFormat": "Read Hit Rate"
      },
      {
       "expr": "rate(flashCacheWriteHitRate{job=~'$JobName',instance=~'$Device',flashCacheSSDDev=~'$flashCacheDisk'}[$__rate_interval])",
       "legendFormat": "Write Hit Rate"
      }
     ]
    },
    {
     "title": "Read/Write Skips: $flashCacheDisk- ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 276 },
     "targets": [
      {
       "expr": "rate(flashCacheReadSeqSkip{job=~'$JobName',instance=~'$Device',flashCacheSSDDev=~'$flashCacheDisk'}[$__rate_interval])",
       "legendFormat": "Read Skips"
      },
      {
       "expr": "rate(flashCacheWriteSeqSkip{job=~'$JobName',instance=~'$Device',flashCacheSSDDev=~'$flashCacheDisk'}[$__rate_interval])",
       "legendFormat": "Write Skips"
      }
     ]
    },
    {
     "title": "Write Misses: $flashCacheDisk- ($Device)",
     "type": "timeseries",
     "description": "The number of\ndata writes to SSD\nfor the first time",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 276 },
     "targets": [
      {
       "expr": "rate(flashCacheWriteMissSsd{job=~'$JobName',instance=~'$Device',flashCacheSSDDev=~'$flashCacheDisk'}[$__rate_interval])",
       "legendFormat": "Write Misses"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory: $hrMemoryDescr - ($Device)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "repeat": "hrMemoryDescr",
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Size",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 461 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hrStorageSize{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrMemoryDescr'} * hrStorageAllocationUnits{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrMemoryDescr'}"
      }
     ]
    },
    {
     "title": "Memory Usage: $hrMemoryDescr ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 21, "x": 3, "y": 461 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "hrStorageSize{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrMemoryDescr'} * hrStorageAllocationUnits{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrMemoryDescr'}",
       "legendFormat": "Size"
      },
      {
       "expr": "hrStorageUsed{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrMemoryDescr'} * hrStorageAllocationUnits{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrMemoryDescr'}",
       "legendFormat": "Used"
      },
      {
       "expr": "(hrStorageSize{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrMemoryDescr'} -  hrStorageUsed{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrMemoryDescr'}) * hrStorageAllocationUnits{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrMemoryDescr'}\n",
       "legendFormat": "Free"
      }
     ]
    },
    {
     "title": "% Used Space",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 463 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(hrStorageUsed{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrMemoryDescr'} /hrStorageSize{job=~'$JobName',instance=~'$Device',hrStorageDescr=~'$hrMemoryDescr'})*100",
       "legendFormat": "% Used"
      }
     ]
    }
   ]
  },
  {
   "title": "Networking: ($Interface) - ($Device)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 },
   "repeat": "Interface",
   "collapsed": true,
   "panels": [
    {
     "title": "Interfaces Details: $Interface - ($Device)",
     "type": "table",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 887 },
     "targets": [
      {
       "expr": "ifPhysAddress{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}"
      },
      {
       "expr": "ifAdminStatus{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}"
      },
      {
       "expr": "ifConnectorPresent{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}"
      },
      {
       "expr": "ifSpeed{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}"
      },
      {
       "expr": "ifOperStatus{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}"
      }
     ]
    },
    {
     "title": "Traffic: $Interface - ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 890 },
     "targets": [
      {
       "expr": "rate(ifHCInOctets{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}[$__rate_interval])*$interfacebits",
       "legendFormat": "Traffic In"
      },
      {
       "expr": "rate(ifHCOutOctets{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}[$__rate_interval])*$interfacebits",
       "legendFormat": "Traffic Out"
      }
     ]
    },
    {
     "title": "Multicast & Broadcast: $Interface - ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 898 },
     "targets": [
      {
       "expr": "rate(ifHCInBroadcastPkts{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}[$__rate_interval])*$interfacebits",
       "legendFormat": "Broadcast In"
      },
      {
       "expr": "rate(ifHCOutBroadcastPkts{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}[$__rate_interval])*$interfacebits",
       "legendFormat": "Broadcast  Out"
      },
      {
       "expr": "rate(ifHCInMulticastPkts{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}[$__rate_interval])*$interfacebits",
       "legendFormat": "Multicast  In"
      },
      {
       "expr": "rate(ifHCOutMulticastPkts{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}[$__rate_interval])*$interfacebits",
       "legendFormat": "Multicast  Out"
      }
     ]
    },
    {
     "title": "Errors $Interface: - ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 898 },
     "targets": [
      {
       "expr": "rate(ifInDiscards{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}[$__rate_interval])",
       "legendFormat": "Discards In"
      },
      {
       "expr": "rate(ifInErrors{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}[$__rate_interval])",
       "legendFormat": "Errors In"
      },
      {
       "expr": "rate(ifOutDiscards{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}[$__rate_interval])",
       "legendFormat": "Discards Out"
      },
      {
       "expr": "rate(ifOutErrors{job=~'$JobName',instance=~'$Device',ifName=~'$Interface'}[$__rate_interval])",
       "legendFormat": "Errors Out"
      }
     ]
    }
   ]
  },
  {
   "title": "Volume: $spaceIODevice - ($Device)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 },
   "repeat": "spaceIODevice",
   "collapsed": true,
   "panels": [
    {
     "title": "Volume Throughput - $spaceIODevice ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(spaceIONReadX{job=~'$JobName',instance=~'$Device',spaceIODevice=~'$spaceIODevice'}[$__rate_interval])",
       "legendFormat": "Read Bytes"
      },
      {
       "expr": "rate(spaceIONWrittenX{job=~'$JobName',instance=~'$Device',spaceIODevice=~'$spaceIODevice'}[$__rate_interval])",
       "legendFormat": "Written Bytes"
      }
     ]
    },
    {
     "title": "Volume IOPS - $spaceIODevice ($Device)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(spaceIOReads{job=~'$JobName',instance=~'$Device',spaceIODevice=~'$spaceIODevice'}[$__rate_interval])",
       "legendFormat": "Read Bytes"
      },
      {
       "expr": "rate(spaceIOWrites{job=~'$JobName',instance=~'$Device',spaceIODevice=~'$spaceIODevice'}[$__rate_interval])",
       "legendFormat": "Written Bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "SMART - ($SmartDev)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 },
   "repeat": "SmartDev",
   "collapsed": true,
   "panels": [
    {
     "title": "S.M.A.R.T: $SmartDev (Data is from the last time the Scheduled task was run)",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3404 },
     "targets": [
      {
       "expr": "diskSMARTInfoDevName{job=~'$JobName',instance=~'$Device',diskSMARTInfoDevName='$SmartDev'}",
       "legendFormat": "AttrName"
      },
      {
       "expr": "diskSMARTAttrName{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "AttrName"
      },
      {
       "expr": "diskSMARTAttrCurrent{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "AttrName"
      },
      {
       "expr": "diskSMARTAttrThreshold{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "AttrName"
      },
      {
       "expr": "diskSMARTAttrWorst{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "AttrName"
      },
      {
       "expr": "diskSMARTAttrStatus{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "Status"
      },
      {
       "expr": "diskSMARTAttrRaw{job=~'$JobName',instance=~'$Device'}",
       "legendFormat": "RAW"
      }
     ]
    }
   ]
  }
 ]
}