# See https://github.com/helm/chart-testing#configuration
remote: origin
target-branch: main
chart-dirs:
  - cronjob
  - proxy
  - grafana-dashboards
  - openvpn-exporter
  - ihm
  - gatus

chart-repos:
  - custom-charts=https://freuds.github.io/custom-charts

lint-conf: lintconf.yaml
validate-maintainers: false
check-version-increment: true
debug: true
