{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "openvpn-exporter.fullname" . }}
  namespace: {{ template "openvpn-exporter.namespace" . }}
  labels:
    {{- include "openvpn-exporter.labels" . | indent 4 }}
data:
  snmp.yaml: |
{{ .Values.config | indent 4 }}
{{- end }}
