{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "openvpn-exporter.labels" . | indent 4 }}
  name: {{ template "openvpn-exporter.serviceAccountName" . }}
  namespace: {{ template "openvpn-exporter.namespace" . }}
{{- end -}}
