name: Helm Charts Release

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
      - '.github/workflows/helm-release.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'charts/**'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Create docs directory if not exists
        run: mkdir -p docs

      - name: Package all charts
        run: |
          for chart in charts/*/Chart.yaml; do
            chart_dir=$(dirname "$chart")
            helm dependency update "$chart_dir" || true
            helm package "$chart_dir" -d docs/
          done

      - name: Generate Helm index.yaml
        run: |
          helm repo index docs/ --url "https://freuds.github.io/custom-charts/"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: helm-charts
          path: docs/
          retention-days: 1

  publish:
    needs: build
    if: |
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main' &&
      github.actor == 'github-page' &&
      contains(github.event.head_commit.message, 'Merge pull request')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: helm-charts
          path: docs/

      - name: Configure Git
        run: |
          git config --global user.name 'github-page'
          git config --global user.email 'github-page@users.noreply.github.com'

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: 'ci: package helm charts and update index.yaml [skip ci]'
          branch: main
          file_pattern: 'docs/*'
          commit_user_name: 'github-page'
          commit_user_email: 'github-page@users.noreply.github.com'
          commit_author: 'github-page <github-page@users.noreply.github.com>'
